### ISSUE TITLE
Local Song cover photo

### ISSUE THREAD

**Issue by akashi7** [tindoescode/react-native-music-player#1]
Hey
Was wondering how you got music cover photo using expo-media-library

In the assets properties i didn't see a propertie matching the image

Thanks

**Comment by tinwritescode** [comment]
> Hey
> Was wondering how you got music cover photo using expo-media-library
> 
> In the assets properties i didn't see a propertie matching the image
> 
> Thanks

Hi akashi7, I use this:
https://github.com/mybigday/react-native-media-meta

also check that line: https://github.com/tindoescode/react-native-music-player/blob/651dfaaf99319b1d5520f5faf17a90c471836d24/app/context/AudioProvider.js#L71

Hope this helps you..😍
